stack.yaml
tensorflow-nn/Setup.hs
tensorflow-nn/src/TensorFlow/NN.hs
tensorflow-nn/tensorflow-nn.cabal
tensorflow-nn/tests/NNTest.hs

- Added "sigmoidCrossEntropyWithLogits"
- Ported across a single test
fixes #10 (well, it adds a single function, and it's a place to start.)
the test could probably be cleaned up quite a bit; happy to do that later on, just wanted to get this up.

Starting NN library

---

README.md
ci_build/outer_launch_tests.sh
tensorflow-nn/tests/NNTest.hs

Sorted test names to make rebuilding meaning.

Fixed CI and added indicator.

---

tensorflow-opgen/src/TensorFlow/OpGen.hs
tensorflow/src/TensorFlow/BuildOp.hs
tensorflow/src/TensorFlow/Output.hs

Exposed by moving to newer TF.

Support ResourceHandle.

---

tensorflow-ops/src/TensorFlow/EmbeddingOps.hs
tensorflow-ops/tests/EmbeddingOpsTest.hs

see https://github.com/tensorflow/haskell/issues/19
this fails. i expect that it should work and that it should result in the given output and shape.
~~once this test works, i'll need to make sure it actually properly checks the shape (at this point this can only be done correctly as a tensorflow op, because we can't yet get back multi-dim vectors https://github.com/tensorflow/haskell/issues/13)~~

added failing test

---

tensorflow-ops/src/TensorFlow/EmbeddingOps.hs
tensorflow-ops/tests/EmbeddingOpsTest.hs

@silky I added a fix on top of your commit. Care to review?

Embedding lookup fix

---

tensorflow-ops/tensorflow-ops.cabal
tensorflow-ops/tests/TracingTest.hs
tensorflow/src/TensorFlow/Core.hs
tensorflow/src/TensorFlow/Session.hs

Still missing a test and a benchmark.
@silky, this should be better than the patch I previously suggested.

Added sessionTracer to log graph operations.

---

tensorflow-core-ops/Setup.hs
tensorflow/src/TensorFlow/Internal/Raw.chs

Includes temporary blacklisting for a couple of ops that will be
supported once my fix lands in the main tensorflow repo.

Uprev tensorflow.

---

tensorflow-opgen/src/TensorFlow/OpGen.hs
tensorflow-opgen/src/TensorFlow/OpGen/ParsedOp.hs
tensorflow-ops/src/TensorFlow/Ops.hs

Also make TensorFlow.Ops.{variable,assign} be the Core generated versions.

Fix Ref and Build semantics for generated code.

---

ci_build/Dockerfile
ci_build/outer_launch_tests.sh
tensorflow-proto/tensorflow-proto.cabal

Needed to list a newly added proto in cabal file.

Updated TensorFlow.

---

README.md
tensorflow-ops/examples/Regression.hs
tensorflow-ops/tensorflow-ops.cabal
tensorflow-ops/tests/RegressionTest.hs

Let me know if you have any better ideas for a "just show me some code" sort of example.

Add example to README + make haddock link more prominent

---

README.md
ci_build/Dockerfile
ci_build/outer_launch_tests.sh
docker/Dockerfile
tensorflow-core-ops/Setup.hs
tensorflow-core-ops/tensorflow-core-ops.cabal
tensorflow/tensorflow.cabal

* Download protoc and libtensorflow instead of running bazel.

Uprev to TF 1.0rc1.

---

README.md
tools/get_mnist_webarchive.sh
tools/install_osx_dependencies.sh

Added a script under tools/ to carry out OSX dependency installation steps https://github.com/tensorflow/haskell#build-on-mac-os-x

Added installation script for OSX dependencies under tools/

---

tensorflow-ops/src/TensorFlow/Ops.hs
tensorflow-ops/tests/OpsTest.hs

The bug was introduced in #84.

Prevent CSE of placeholder ops.

---

stack.yaml
tensorflow-core-ops/tensorflow-core-ops.cabal
tensorflow-logging/tensorflow-logging.cabal
tensorflow-logging/tests/LoggingTest.hs
tensorflow-mnist/tensorflow-mnist.cabal
tensorflow-opgen/tensorflow-opgen.cabal
tensorflow-ops/tensorflow-ops.cabal
tensorflow-proto/tensorflow-proto.cabal
tensorflow-queue/tensorflow-queue.cabal
tensorflow/src/TensorFlow/Session.hs
tensorflow/src/TensorFlow/Types.hs
tensorflow/tensorflow.cabal

Squashed previous pull request

Adapt to lts-8.6 and use proto-lens-0.2.0.1

---

tensorflow-ops/src/TensorFlow/Variable.hs
tensorflow-ops/tests/VariableTest.hs

Also add a unit test corresponding to that comments' example code.

Clarify the behavior of readValue in a comment.

---

tensorflow-ops/tensorflow-ops.cabal
tensorflow-ops/tests/MatrixTest.hs

Added a simple test that factors a 2x2 matrix of rank 1 into the outer product of two vectors.

added matrix factorization test

---

tensorflow-core-ops/Setup.hs

Use the same trick as for `proto-lens-protoc`: hack the package description
during the `sdist` step to include the autogen directory in hs-source-dirs.

Fix 'sdist' for tensorflow-core-ops.

---

tensorflow/tensorflow.cabal

Also bumps up the version of the 'tensorflow' package to 0.1.0.1.

Include c_api.h in the tensorflow sdist.

---

README.md

Added stack version check command.

update readme for checking stack version

---

tensorflow-ops/src/TensorFlow/Gradient.hs
tensorflow-ops/tensorflow-ops.cabal
tensorflow-ops/tests/GradientTest.hs

Hi,
This pull request adds the gradient for Concat ops. Any feedback or suggestions are welcome.
Jonathan

Adding gradient for Concat

---

ChangeLog.md
ci_build/Dockerfile
docker/Dockerfile
tensorflow-core-ops/Setup.hs
tensorflow-mnist/app/Main.hs
tensorflow-proto/tensorflow-proto.cabal
tensorflow/src/TensorFlow/Types.hs
tools/install_macos_dependencies.sh
tools/userchroot.nix

* Tested on linux without Docker.
* Couldn't get nix build to work, so I just updated the URL and hash.
* Did not test macos build.
The mnist change was necessary because the argmax output type is now polmorphic.

Update to tensorflow 1.3

---

ci_build/Dockerfile
docker/Dockerfile
docker/gpu/Dockerfile

i changed maintainer to label, since the former is deprecated.
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
All the best,
Benjamin

change MAINTAINER to LABEL

---

README.md

Update version number in Link (404 on old Link)

Update Link to TensorFlow.Core

---

README.md

Happy to change the wording if anyone has suggestions.

Add link to tensorflow-haskell-deptyped to README

---

README.md

https://github.com/tensorflow/haskell/issues/156

Add tensorflow-haskell-deptyped example

---

ChangeLog.md

Update changelog for v0.2.0.0

---

ChangeLog.md
tensorflow-core-ops/tensorflow-core-ops.cabal
tensorflow-logging/tensorflow-logging.cabal
tensorflow-mnist/tensorflow-mnist.cabal
tensorflow-opgen/tensorflow-opgen.cabal
tensorflow-ops/tensorflow-ops.cabal
tensorflow-proto/tensorflow-proto.cabal
tensorflow/tensorflow.cabal

https://github.com/tensorflow/haskell/issues/193

Bump all of the versions to 0.2.0.0

---

tensorflow-ops/src/TensorFlow/Gradient.hs
tensorflow-ops/src/TensorFlow/Ops.hs
tensorflow-ops/tests/GradientTest.hs

The CLA is signed by the manager of my company, Active Group GmbH. Please let me know if more info is needed.

Added support for tanh activation function

---

nix/src.json
nix/update
shell.nix
stack.yaml
tensorflow-opgen/src/TensorFlow/OpGen.hs

Upgraded Stackage resolver to LTS-12 (GHC 8.4.4) 

---

tensorflow-ops/src/TensorFlow/Gradient.hs
tensorflow-ops/tests/GradientTest.hs

I added the gradient for the `sqrt` function. Please check if the implementation is right.

Add gradient for sqrt function

---

tensorflow-core-ops/Setup.hs
tensorflow-core-ops/tensorflow-core-ops.cabal

Just conditionally remove sDistHook in that case.

Unbreak build with Cabal >= 2.4.

---

tensorflow-ops/src/TensorFlow/Variable.hs
tensorflow-ops/tests/EmbeddingOpsTest.hs
tensorflow-ops/tests/GradientTest.hs

These are all MonadFail-related.

Fix compile on ghc 8.8.
