tensorflow/haskell

tensorflow/src/TensorFlow/Internal/Raw.chs
In particular, this helps fix the build on Mac OS X which seems to unconditionally define it that way (even on 64-bit).
=> Compile on platforms where int64_t == long long.

tensorflow-ops/src/TensorFlow/Ops.hs, tensorflow-ops/tensorflow-ops.cabal, tensorflow-ops/tests/MiscTest.hs
topK is obsolete and generating warnings.
=> Replaced topK with topKV2.

docker/Dockerfile
Unfortunately blaze build is notably slower to run.
=> Resolve #30 by using nightly.

tensorflow-core-ops/Setup.hs, tensorflow/src/TensorFlow/Internal/FFI.hs
* No longer need to hide ResourceHandle ops
* Blacklisted not supported TensorArrayV2
* Ownership of feed tensors changed (TF commit 1f0c5119a0230c5160d45496175b9256f097e144)
=> Uprev tensorflow.

.gitignore, tensorflow-ops/tensorflow-ops.cabal, tensorflow-ops/tests/FeedFetchBench.hs, tensorflow/src/TensorFlow/Internal/FFI.hs
```
benchmarking feedFetch/4 byte
time                 56.07 μs   (54.64 μs .. 57.31 μs)
0.995 R²   (0.993 R² .. 0.997 R²)
mean                 57.66 μs   (56.57 μs .. 58.74 μs)
std dev              3.851 μs   (3.350 μs .. 4.642 μs)
variance introduced by outliers: 68% (severely inflated)
benchmarking feedFetch/4 KiB
time                 228.8 μs   (227.4 μs .. 230.3 μs)
0.999 R²   (0.999 R² .. 1.000 R²)
mean                 229.1 μs   (228.5 μs .. 230.5 μs)
std dev              3.016 μs   (1.902 μs .. 5.111 μs)
benchmarking feedFetch/4 MiB
time                 596.5 ms   (457.2 ms .. 661.2 ms)
0.994 R²   (0.984 R² .. 1.000 R²)
mean                 569.8 ms   (536.0 ms .. 589.7 ms)
std dev              30.62 ms   (0.0 s .. 34.45 ms)
variance introduced by outliers: 19% (moderately …
```
=> Optimize fetching

stack.yaml, tensorflow-nn/tensorflow-nn.cabal, tensorflow-nn/tests/NNTest.hs, tensorflow-ops/src/TensorFlow/Gradient.hs, tensorflow-ops/src/TensorFlow/Ops.hs, tensorflow-ops/tensorflow-ops.cabal, tensorflow-ops/tests/EmbeddingOpsTest.hs, tensorflow-test/Setup.hs, tensorflow-test/src/TensorFlow/Test.hs, tensorflow-test/tensorflow-test.cabal
i've noticed that i don't seem to be able to calculate the gradient w.r.t an embedding, this is the error:
```
ERROR: TensorFlowException TF_INVALID_ARGUMENT "Expected begin and size arguments to be 1-D tensors of size 1, but got shapes [] and [] instead.
[[Node: Slice_54 = Slice[Index=DT_INT32, T=DT_INT32, _device=\"/job:localhost/replica:0/task:0/cpu:0\"](Shape_52, Const_18, Neg_53)]]"
```
the equivalent python code to the following test works (but i note that in python i can *also* calculate the gradient w.r.t say the variable named below called `op` that is a `Tensor Value` not a `Tensor Ref`; i.e. it's a type error)
i'm looking for a bit of guidance here. i'm fairly sure i should be able to calculate the gradient like this. but i could be convinced/shown that i'm doing it wrong, and …
=> test case to show can't calculate grad for embedding (and associated fix)

tensorflow-core-ops/tensorflow-core-ops.cabal, tensorflow-nn/tensorflow-nn.cabal, tensorflow-ops/tensorflow-ops.cabal, tensorflow/src/TensorFlow/Types.hs
Two issues:
- The definition of `\\` was missing parentheses.  It was probably a bug
that this used to worked in ghc-7.10.
- Set -fconstraint-solver-iterations=0 to work around
https://ghc.haskell.org/trac/ghc/ticket/12175.  It looks like we can
trigger that bug when defining a significantly complicated op.  Specifically,
our type shenanigans ("OneOf") along with lens setters (for OpDef) seem
to confuse GHC.
Still TODO: automate testing of different ghc versions to prevent a regression.
=> Fix the build on ghc-8.0.1 (#38).

README.md
I'm not sure why, but in some cases it seems linking only works if *both* the
.so and the .dylib are present in /usr/local/lib.  This may be due to a quirk
of how Bazel builds the library, and/or how ghc/stack load the library.
=> Add instructions to symlink ".so" to ".dylib" on OS X (#42).

README.md
The right approach is to run `install_name_tool` on the library after renaming
its extension from ".so" to ".dylib".
=> Update OS X instructions (#42) to not require a separate ".so" file.

ci_build/Dockerfile, ci_build/outer_launch_tests.sh
The script can now be run with, e.g.
`env STACK_RESOLVER=lts-7.3 ci_build/outer_launch_tests.sh`
and will use the specified version of the resolver.
We can't quite enable this for lts-7.3 as the code is not pedantically
clean. We will reconsider when 8.0.2 is available which removes
`-Wredundant-constraints` from `-Wall`.
=> Add stack resolver version switch (#38).

tensorflow-core-ops/tensorflow-core-ops.cabal, tensorflow-nn/src/TensorFlow/NN.hs, tensorflow-nn/tensorflow-nn.cabal, tensorflow-opgen/src/TensorFlow/OpGen.hs, tensorflow-ops/src/TensorFlow/EmbeddingOps.hs, tensorflow-ops/src/TensorFlow/Ops.hs, tensorflow-ops/tensorflow-ops.cabal, tensorflow-ops/tests/TypesTest.hs, tensorflow/src/TensorFlow/Types.hs
Also removes all the ghc-8-specific logic in the .cabal files.
ghc-8 has issues with deeply nested tuples of constraints.  We can
work around it by:
- Changing TensorTypes to a regular class.  This required FlexibleContexts.
(But we'll probably need it anyway when we support heterogeneous tensor
lists.)
- Specializing NoneOf for long type lists.
For more details, see: https://ghc.haskell.org/trac/ghc/ticket/12175.
Also added 'directory' to tensorflow-core-ops' dependencies since it's used
in the Setup script.
=> Update type constraints to work around a ghc-8 bug.

tensorflow-mnist/app/Main.hs, tensorflow-mnist/tests/ParseTest.hs, tensorflow-ops/tests/BuildTest.hs, tensorflow-ops/tests/DataFlowOpsTest.hs, tensorflow-ops/tests/EmbeddingOpsTest.hs, tensorflow-ops/tests/FeedFetchBench.hs, tensorflow-ops/tests/TypesTest.hs, tensorflow-queue/tests/QueueTest.hs, tensorflow/src/TensorFlow/Core.hs, tensorflow/src/TensorFlow/Nodes.hs, tensorflow/src/TensorFlow/Types.hs
In addition, you can now fetch TensorData directly. This might be useful in
scenarios where you feed the result of a computation back in, like RNN.
Before:
benchmarking feedFetch/4 byte
time                 83.31 μs   (81.88 μs .. 84.75 μs)
0.997 R²   (0.994 R² .. 0.998 R²)
mean                 87.32 μs   (86.06 μs .. 88.83 μs)
std dev              4.580 μs   (3.698 μs .. 5.567 μs)
variance introduced by outliers: 55% (severely inflated)
benchmarking feedFetch/4 KiB
time                 114.9 μs   (111.5 μs .. 118.2 μs)
0.996 R²   (0.994 R² .. 0.998 R²)
mean                 117.3 μs   (116.2 μs .. 118.6 μs)
std dev              3.877 μs   (3.058 μs .. 5.565 μs)
variance introduced by outliers: 31% (moderately inflated)
benchmarking feedFetch/4 MiB
time                 109.0 ms   (107.9 ms …
=> Support fetching storable vectors + use them in benchmark

tensorflow-core-ops/Setup.hs, tensorflow-opgen/src/TensorFlow/OpGen/ParsedOp.hs
We should treat such attributes as regular `DataType` values rather than type
parameters; otherwise we'll get ambiguous types.  As with other attributes,
they can either set by default or passed in as an explicit argument to the op.
Allows us to reenable a couple more ops.
=> Support type attributes that aren't used by an input/output.

ci_build/Dockerfile, docker/Dockerfile, stack.yaml, tensorflow-records-conduit/Setup.hs, tensorflow-records-conduit/src/TensorFlow/Records/Conduit.hs, tensorflow-records-conduit/tensorflow-records-conduit.cabal, tensorflow-records/Setup.hs, tensorflow-records/src/TensorFlow/CRC32C.hs, tensorflow-records/src/TensorFlow/Records.hs, tensorflow-records/tensorflow-records.cabal, tensorflow-records/tests/Main.hs
The tensorflow-records package implements encoding/decoding of the
format, and the tensorflow-records-conduit package provides wrappers and
utilities for use with Conduit.
Thanks to @fkm3 for finding a native CRC32C implementation and writing the Cabal and Stack config for these packages.
Intended to supersede #70.
=> Add tensorflow-records and tensorflow-records-conduit packages.

README.md, stack.yaml
- Use the prebuilt binaries/headers for TF 1.0rc.
- Add instructions and stack.yaml config for tensorflow-records's dependency on
snappy.
=> Update Mac build instructions.

tensorflow-core-ops/Setup.hs, tensorflow-opgen/src/TensorFlow/OpGen.hs, tensorflow-opgen/src/TensorFlow/OpGen/ParsedOp.hs, tensorflow-queue/src/TensorFlow/Queue.hs, tensorflow-queue/tests/QueueTest.hs, tensorflow/src/TensorFlow/BuildOp.hs, tensorflow/src/TensorFlow/Nodes.hs, tensorflow/src/TensorFlow/Tensor.hs, tensorflow/src/TensorFlow/Types.hs
Adds a new type `ListOf` which wraps a heterogeneous list; for example,
`ListOf (Tensor Value) '[Int32, Float]` represents a list of two
elements: a tensor of int32s and a tensor of floats.
Also changes the `Queue2` type (which suppored pairs of tensors) to
`Queue` (which supports arbitrary lists).
=> Support lists of tensors in ops.

README.md, tensorflow-mnist/tests/ParseTest.hs, tensorflow-nn/src/TensorFlow/NN.hs, tensorflow-nn/tests/NNTest.hs, tensorflow-opgen/src/TensorFlow/OpGen.hs, tensorflow-ops/src/TensorFlow/EmbeddingOps.hs, tensorflow-ops/src/TensorFlow/Gradient.hs, tensorflow-ops/src/TensorFlow/Ops.hs, tensorflow-ops/tests/BuildTest.hs, tensorflow-ops/tests/DataFlowOpsTest.hs, tensorflow-ops/tests/EmbeddingOpsTest.hs, tensorflow-ops/tests/GradientTest.hs, tensorflow-ops/tests/OpsTest.hs, tensorflow-ops/tests/RegressionTest.hs, tensorflow-ops/tests/TracingTest.hs, tensorflow-queue/src/TensorFlow/Queue.hs, tensorflow-queue/tensorflow-queue.cabal, tensorflow-queue/tests/QueueTest.hs, tensorflow/src/TensorFlow/Build.hs, tensorflow/src/TensorFlow/ControlFlow.hs, tensorflow/src/TensorFlow/Core.hs, tensorflow/src/TensorFlow/Session.hs
This change adds a class that both `Build` and `Session` are instances of:
class MonadBuild m where
build :: Build a -> m a
All stateful ops (generated and manually written) now have a signature that returns
an instance of `MonadBuild` (rather than just `Build`).  For example:
assign_ :: (MonadBuild m, TensorType t)
=> Tensor Ref t -> Tensor v t -> m (Tensor Ref t)
This lets us remove a bunch of spurious calls to `build` in user code.  It also
lets us replace the pattern `buildAnd run foo` with the simpler pattern `foo >>= run`
(or `run =<< foo`, which is sometimes nicer when foo is a complicated expression).
I went ahead and deleted `buildAnd` altogether since it seems to lead to
confusion; in particular a few tests had `buildAnd run . pure` which is
actually equivalent to just `run`.
=> Introduce a MonadBuild class, and remove `buildAnd`.

tensorflow-opgen/src/TensorFlow/OpGen.hs, tensorflow-ops/src/TensorFlow/Gradient.hs, tensorflow-ops/src/TensorFlow/Ops.hs, tensorflow-ops/tests/BuildTest.hs, tensorflow-ops/tests/OpsTest.hs, tensorflow-ops/tests/TypesTest.hs, tensorflow/src/TensorFlow/BuildOp.hs, tensorflow/src/TensorFlow/ControlFlow.hs, tensorflow/src/TensorFlow/Core.hs, tensorflow/src/TensorFlow/Output.hs, tensorflow/src/TensorFlow/Tensor.hs
Each op `foo :: ...` now has a corresponding `foo' :: OpParams -> ...`
which lets you set optional attributes.  `OpParams` is currently a type alias for
`OpDef -> OpDef`.  In the future we should consider more type safety, e.g.,
using type-level strings and OverloadedLabels for optional attributes.
I used it to replace a few manual `buildOp`s in our code with the codegenerated
ops, now that it's easier to set attributes.  I also removed `tensorAttr` and
`named` since it's now possible to set those op attributes directly.
Although this clutters up the API a bit, I think it's simpler than using type
classes to implement optional arguments (as in, for example, `Text.Printf`) --
especially in terms of type inference with the rest of the library.
=> Add versions of each op that take optional params as an extra arg.

tensorflow-ops/tests/OpsTest.hs
As a follow-up to #86, check that our CSE isn't too aggressive to prevent feeds
of pure ops with distinct names.
=> Add another test of CSE and feeds.

tools/install_osx_dependencies.sh
previously I was getting the following error:
./: Can't update time for .
tar: Error exit delayed from previous errors.
=> call sudo consistently within OSX build script

README.md, tensorflow-logging/src/TensorFlow/Logging.hs, tensorflow-mnist/app/Main.hs, tensorflow-mnist/tests/ParseTest.hs, tensorflow-nn/src/TensorFlow/NN.hs, tensorflow-nn/tests/NNTest.hs, tensorflow-opgen/src/TensorFlow/OpGen.hs, tensorflow-opgen/src/TensorFlow/OpGen/ParsedOp.hs, tensorflow-ops/src/TensorFlow/EmbeddingOps.hs, tensorflow-ops/src/TensorFlow/Gradient.hs, tensorflow-ops/src/TensorFlow/Ops.hs, tensorflow-ops/tensorflow-ops.cabal, tensorflow-ops/tests/ArrayOpsTest.hs, tensorflow-ops/tests/BuildTest.hs, tensorflow-ops/tests/DataFlowOpsTest.hs, tensorflow-ops/tests/EmbeddingOpsTest.hs, tensorflow-ops/tests/GradientTest.hs, tensorflow-ops/tests/OpsTest.hs, tensorflow-ops/tests/RegressionTest.hs, tensorflow-ops/tests/TypesTest.hs, tensorflow-queue/src/TensorFlow/Queue.hs, tensorflow/src/TensorFlow/Build.hs, tensorflow/src/TensorFlow/BuildOp.hs, tensorflow/src/TensorFlow/ControlFlow.hs, tensorflow/src/TensorFlow/Core.hs, tensorflow/src/TensorFlow/Nodes.hs, tensorflow/src/TensorFlow/Output.hs, tensorflow/src/TensorFlow/Session.hs, tensorflow/src/TensorFlow/Tensor.hs
There are now three types of `Tensor`:
- `Tensor Value a`: rendered value
- `Tensor Ref a`: rendered reference
- `Tensor Build a` : unrendered value
The extra bookkeeping makes it easier to track (and enforce) which tensors are
rendered or not.  For examples where this has been confusing in the past, see
With this change, pure ops look similar to before, returning `Tensor Build`
instead of `Tensor Value`.  "Stateful" (monadic) ops are unchanged.  For
example:
add :: OneOf [..] t => Tensor v'1 t -> Tensor v'2 t -> Tensor Build t
assign :: (MonadBuild m, TensorType t)
=> Tensor Ref t -> Tensor v'2 t -> m (Tensor Ref t)
The `gradients` function now requires that the variables over which it's
differentiating are pre-rendered:
gradients :: (..., Rendered v2) => Tensor v1 a -> [Tensor v2 a]
-> …
=> Distinguish between "rendered" and "unrendered" Tensors.

tensorflow-opgen/src/TensorFlow/OpGen.hs, tensorflow-opgen/src/TensorFlow/OpGen/ParsedOp.hs, tensorflow-ops/src/TensorFlow/Variable.hs, tensorflow-ops/tensorflow-ops.cabal, tensorflow-ops/tests/VariableTest.hs, tensorflow/src/TensorFlow/Build.hs, tensorflow/src/TensorFlow/BuildOp.hs, tensorflow/src/TensorFlow/Core.hs, tensorflow/src/TensorFlow/Output.hs, tensorflow/src/TensorFlow/Types.hs
The main difference between these and the `Ref`-bases ops is the explicit
`readValue` op.  I'm not sure how this should interact with gradients
and save/restore, so I'm keeping it as a separate module for now.  Once we
figure out the details, we can merge it into `TensorFlow.Ops` and replace
all uses of the old `Ref`-based ops.  (Which will also fix #92.)
Also replaces our special case newtype `ResourceHandle` to
`Tensor Value ResourceHandle`, where `ResourceHandle` is the TF proto
corresponding to `DT_RESOURCE`.
=> Add resource-based variable ops.

tensorflow-ops/src/TensorFlow/Gradient.hs, tensorflow-ops/tests/GradientTest.hs
Implementation of "ReluGradGrad", emulating the python implementation. Implementing gradient of "Fill" was also necessary to get the tests to run. Added two testcases, one for ReluGrad and one for ReluGradGrad.
I am unsure if implementations are correct when it comes to higher dimensionalities etc. Particularly the use of 'sum" in the "Fill" gradient as the python implementation uses math_ops.reduce_sum(grad).
=> Implemented gradient of ReluGrad and Fill

tensorflow-ops/src/TensorFlow/Gradient.hs, tensorflow-ops/src/TensorFlow/Ops.hs, tensorflow-ops/tensorflow-ops.cabal, tensorflow-ops/tests/GradientTest.hs
When `matMul` has `transpose_a` or `transpose_b`, the implementation of `opGrad` for `matMul` gives gradients of different shape than the tensors to regard. This shows up when taking second order gradients.
Added Tests for these issues and implemented fix.
The default untransposed `matMul` gradient was ok.
Also implemented gradient of `Tile`
=> Fix for gradients of matMul with transposed inputs.

tensorflow-ops/tests/OpsTest.hs, tensorflow/src/TensorFlow/Internal/FFI.hs
It would be better to avoid the copy when it's not necessary, but
that will require more involved changes to the internal API.  (For example,
Fetchable might need to allow IO or ST actions.)
=> Work around #92 by always copying TensorData when fetching.

tensorflow-ops/tests/MatrixTest.hs
The number of iterations was reduced from 1000 to 300 during review, but that
turned out to be too low and the test now fails about 20% of the time.
After changing it back to 1000, the test succeeded at 50 out of 50 runs.
=> Increase the number of iterations for MatrixTest.

ci_build/Dockerfile, ci_build/outer_launch_tests.sh, stack.yaml, tensorflow-core-ops/tensorflow-core-ops.cabal, tensorflow-mnist-input-data/tensorflow-mnist-input-data.cabal, tensorflow-proto/tensorflow-proto.cabal
Our packages no longer elicit complaints like this:
Package tensorflow-foo uses a custom Cabal build, but does not use a
custom-setup stanza.
=> Switched to lts-8.13, added custom-setup.

google-shim/LICENSE, google-shim/google-shim.cabal, tensorflow-core-ops/LICENSE, tensorflow-core-ops/tensorflow-core-ops.cabal, tensorflow-logging/LICENSE, tensorflow-logging/tensorflow-logging.cabal, tensorflow-mnist-input-data/LICENSE, tensorflow-mnist-input-data/tensorflow-mnist-input-data.cabal, tensorflow-mnist/LICENSE, tensorflow-mnist/tensorflow-mnist.cabal, tensorflow-nn/LICENSE, tensorflow-nn/tensorflow-nn.cabal, tensorflow-opgen/LICENSE, tensorflow-opgen/tensorflow-opgen.cabal, tensorflow-ops/LICENSE, tensorflow-ops/tensorflow-ops.cabal, tensorflow-proto/LICENSE, tensorflow-proto/Setup.hs, tensorflow-proto/tensorflow-proto.cabal, tensorflow-proto/third_party, tensorflow-queue/LICENSE, tensorflow-queue/tensorflow-queue.cabal, tensorflow-records-conduit/LICENSE, tensorflow-records-conduit/tensorflow-records-conduit.cabal, tensorflow-records/LICENSE, tensorflow-records/tensorflow-records.cabal, tensorflow-test/LICENSE, tensorflow-test/tensorflow-test.cabal, tensorflow/LICENSE, tensorflow/tensorflow.cabal
- Add LICENSE files for all packages.
- Add descriptions for packages that were missing one.
- Work around google/proto-lens#69 by symlinking third_party into
tensorflow-proto.
=> Fix .cabal files so 'stack check' passes.

stack.yaml
As far as I can tell they're not necessary anymore with the current OS X
script that calls `install_name_tool`.  Both "stack test" and "stack ghci"
work without those settings.
=> Remove extra-{include,lib}-dirs from stack.yaml.

tensorflow-ops/src/TensorFlow/EmbeddingOps.hs, tensorflow-ops/src/TensorFlow/Gradient.hs, tensorflow-ops/src/TensorFlow/Ops.hs, tensorflow-ops/src/TensorFlow/Variable.hs, tensorflow/src/TensorFlow/BuildOp.hs, tensorflow/src/TensorFlow/Tensor.hs
This allows functions like `feed`, `colocateWith`, and (in a later commit)
`gradients` to work with `Variable`.
=> Expand Rendered class to support ResourceHandle wrappers like Variable

stack.yaml, tensorflow/tensorflow.cabal
Also bump the version to 0.1.0.2.
Originally we had `extra-lib-dirs: /usr/local/lib` in `stack.yaml`.
I removed it because it wasn't necessary on my Mac.  However,
it turns out that it is necessary for machines with the default installation
of XCode, which *doesn't* search that path by default.
(On my machine, it wasn't necessary because I had run `xcode-select --install`
which adds that path permanently to your search path.)
I'm adding the setting back to `tensorflow.cabal` as well as `stack.yaml` so
that the Hackage release also contains this fix.  Changing `stack.yaml` is
still necessary in order to fix linkage in the `snappy` package (which
`tensorflow-records` depends on).  Hopefully that will go away once we remove
the dependency (#118).
=> Add extra-lib-dirs back into .cabal for Mac builds.

ChangeLog.md, tensorflow/tensorflow.cabal
The HEAD contains #119 which is an API change requiring (as far as I can tell)
a major version bump.
=> Bump version to 0.2.0.0, and start a changelog.

tensorflow-mnist-input-data/Setup.hs
Changing way to download MNIST dataset from Network.HTTP.simpleHTTP to Network.Browser.browse which allows to capture the environment's proxy.
=> Modifying tensorflow-mnist-input-data's setup to download MNIST through http proxy if necessary

README.md
This requirement is due to #106 which added Cabal `custom-setup` clauses.
=> Note that we require stack-1.4.0 or newer.

stack.yaml, tensorflow-proto/tensorflow-proto.cabal
That package now includes everything in the `tensorflow/core:protos_all` target:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/BUILD#L131
I also made all of the modules exposed for simplicity.  (As a particular
example: `MetaGraph`, which was previously in `other-modules`, is useful for
constructing some TensorFlow serving RPCs.)
=> Fill out the modules in tensorflow-proto.

tensorflow-mnist/app/Main.hs, tensorflow-ops/src/TensorFlow/Ops.hs, tensorflow-ops/tests/MatrixTest.hs
`reduceMean` seems to be useful to have in a common location
=> Moved reduceMean to Ops

tensorflow-ops/src/TensorFlow/Gradient.hs, tensorflow-ops/tests/GradientTest.hs
Added gradient of `maximum` with first and second order gradient tests.
Added `gradForBinaryCwise` like the C++ version. This may be of use for other binary component-wise gradient functions.
=> Add gradient of `maximum` and `gradForBinaryCwise`

stack.yaml, tensorflow-core-ops/Setup.hs, tensorflow/src/TensorFlow/Types.hs
- Avoid using a deprecated Cabal function
- Use newer versions of proto-lens packages in stack.yaml
- Work around a new type-level warning that affects `OneOf/TensorTypes`.
=> Fix the build with ghc-8.2.1.

tensorflow-ops/src/TensorFlow/Gradient.hs
=> Fix a small typo in the warning message of numOutputs

tensorflow/src/TensorFlow/Internal/FFI.hs, tensorflow/src/TensorFlow/Session.hs
`Session` was already a monad transformer stack, which is now also exported. All other signatures have become a bit more generic but are all backwards compatible.
=> Create monad transformer version of Session (closes #153)

README.md, docker/gpu/Dockerfile, tools/nvidia-docker-wrapper.sh
This procedure is a bit convoluted, but possible to get utilisation of GPU this way.
=> How to use GPU with stack, docker, nvidia-docker

ci_build/Dockerfile
Not sure if this makes any difference, but it seems like a good idea for consistency.
=> Use newer tensorflow image in ci_build/Docker

tensorflow-ops/src/TensorFlow/Variable.hs, tensorflow-ops/tests/VariableTest.hs, tensorflow/src/TensorFlow/Types.hs
This is needed to support tensorflow 1.7. The trick of initializing a
variable with `Shape []` and then overriding the shape by assigning an
initial value no longer works. It seems that we need to explicitly flip
the `unknown_rank` bit in the shape proto.
I thought about switching opgen to use `Maybe Shape` when an op requires
a shape attribute, but that will cause a lot of api churn, so I chose to
hold off for now and just do a spot fix to unblock 1.7.
The new test assert already passes in the current version, but fails in 1.7.
=> Fix initialized variables for tensorflow 1.7

ChangeLog.md, ci_build/Dockerfile, docker/Dockerfile, tensorflow-core-ops/Setup.hs, tensorflow-opgen/src/TensorFlow/OpGen.hs, tensorflow-ops/src/TensorFlow/Ops.hs, tensorflow/src/TensorFlow/Types.hs, tools/install_macos_dependencies.sh, tools/userchroot.nix
All of the non-`s/1.3/1.7/` changes are because
* There are new tensorflow datatypes
* Some ops have looser types (e.g. `fill` now accepts both int64 and int32)
* There are more ops of type "func"
=> Update to tensorflow 1.7

ChangeLog.md, ci_build/Dockerfile, docker/Dockerfile, docker/gpu/Dockerfile, tensorflow-core-ops/Setup.hs, tools/install_macos_dependencies.sh, tools/userchroot.nix
Updates to tensorflow 1.8. Follows in the footsteps of the commit updating tensorflow to 1.7 (1e2dca870125a2941359f14f5e02971a28d6e199). I have only done light testing, but it seems to work.
(Not sure about the update to the change log. Maybe you'd like to release a version using 1.7 first?)
=> Update to tensorflow 1.8

ci_build/Dockerfile, docker/Dockerfile, tensorflow-ops/tests/GradientTest.hs
Required by #187.
The version we were using is old enough that it doesn't work with the
latest stackage LTS. haskellstack.org says
There is also a Ubuntu package for Ubuntu 16.10 and up, but the
distribution's Stack version lags behind, ...
So, instead of asking them to update it, it's probably better to
download the tar of the version we want.
Somehow updating stack surfaced a new pedantic warning in GradientTest,
so I've fixed that as well (and cleaned up some code using snake_case).
=> Use newer version of stack in CI

tools/install_macos_dependencies.sh
Hi,
this is a small fix that allows a clean installation on OSX High Sierra/Sierra/El Capitan due to the limitations Apple introduced to write to /usr folder even for root.
=> Fix install script for High Sierra

nix/src.json, shell.nix
* I upgraded nixpkgs to the [latest master which now contains `libtensorflow`](https://github.com/NixOS/nixpkgs/blob/7098bcac278a2d028036bb3a23508fd1c52155ac/pkgs/development/libraries/libtensorflow/default.nix). This replaces the custom `tensorflow-c`. Note that `libtensorflow` now also builds on OS X and has optional CUDA support.
* nixpkgs is now pinned using `builtins.fetchTarball` which means we can build with an empty `NIX_PATH` thus making the build pure.
This does require Nix-2.0 but this has been released for a while with NixOS-18.03.
* The stack override has been replaced by passing `extraArgs = "--system-ghc";` to `buildStackProject`.
BTW I also added [overrides for the tensorflow-haskell packages to nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell- …
=> Simplified shell.nix

README.md, tools/haddock.sh
Hello.
I was reading the README and clicked on the link to see `TensorFlow.Core` and the link took me to a 404 page. The URL had `0.1.0.2` and when I changed it to the latest release version everything worked.
=> Update README link to point to the most recent release docs

tensorflow-ops/src/TensorFlow/Gradient.hs, tensorflow-ops/tests/GradientTest.hs
The implementation of the gradient for `expandDims` is the same as for `reshape`.
Also added missing gradient test for `reshape`.
=> Added support for ExpandDims gradient.

tensorflow-ops/src/TensorFlow/Gradient.hs, tensorflow-ops/tests/GradientTest.hs
Please check if the implementation is right.
=> Added support for the gradient of the pad function.

tensorflow-ops/src/TensorFlow/Gradient.hs, tensorflow-ops/tests/GradientTest.hs
I added the gradient for the slice function in tensorflow / haskell. Please check if the implementation is right. I used the version in python for template, see array_grad.py.
The CLA is signed by the manager of my company, Active Group GmbH. Please let me know if more info is needed (same as with pull requests by @rikvdkleij).
=> Add gradient for slice function

tensorflow-ops/src/TensorFlow/Gradient.hs, tensorflow-ops/tests/GradientTest.hs
This implements a TODO by fmayle
The `testGradientIncidental` has an incidental "Diag" node, which has no `opGrad` implementation. Since the Diag node is not a successor of the 'x' we want gradient for, it won't be visited.
I removed two `opGrad` implementations as suggested by comments by fmayle. This may be a breaking change, and I'm open to putting these back if needed.
=> Avoid computing gradients for incidental nodes

tensorflow-core-ops/tensorflow-core-ops.cabal, tensorflow-logging/tensorflow-logging.cabal, tensorflow-mnist/tensorflow-mnist.cabal, tensorflow-opgen/tensorflow-opgen.cabal, tensorflow-ops/tensorflow-ops.cabal, tensorflow-proto/tensorflow-proto.cabal, tensorflow/tensorflow.cabal
I confirmed that it still builds with 0.5.
=> Bump version constraints for proto-lens-*

nix/src.json, nix/update, shell.nix
With @curiousleo, we have noticed some outdated versions in installation by nix. 
We did the following changes:
* `nix/update` updated to pull from the nix release `19.09`
* `shell.nix` updated to use `ghc865` as default for `ghc` (since `LTS14.4` uses `ghc865`).
=> nix updated to be compatible with LTS14.4

README.md
We can share the GCS bucket for build badges with other TensorFlow repositories.
Underlying migration is still in progress and please do not merge until the badge appears on the new location.
=> Updates the build badge path to the new location.

README.md, ci_build/Dockerfile, docker/Dockerfile, docker/gpu/Dockerfile, stack.yaml, tensorflow-core-ops/Setup.hs, tensorflow-core-ops/tensorflow-core-ops.cabal, tensorflow-logging/tensorflow-logging.cabal, tensorflow-mnist-input-data/tensorflow-mnist-input-data.cabal, tensorflow-mnist/tensorflow-mnist.cabal, tensorflow-opgen/tensorflow-opgen.cabal, tensorflow-ops/tensorflow-ops.cabal, tensorflow-proto/tensorflow-proto.cabal, tensorflow-records-conduit/tensorflow-records-conduit.cabal, tensorflow-records/tensorflow-records.cabal, tensorflow-test/tensorflow-test.cabal, tensorflow/src/TensorFlow/Internal/FFI.hs, tensorflow/src/TensorFlow/Internal/Raw.chs, tensorflow/src/TensorFlow/Types.hs, tensorflow/tensorflow.cabal
](https://github.com/tensorflow/tensorflow/releases/tag/v2.4.0) (breaking change; fixes `QueueTest` in `tensorflow-ops`)
=> Update to TensorFlow 2.10.1

tensorflow/src/TensorFlow/Internal/VarInt.hs, tensorflow/tensorflow.cabal
`Data.ByteString.Lazy.Builder` has been removed.
=> Fix build for GHC 9.2

README.md
The link to the `TensorFlow.Core` documentation in the README seems to be incorrect which this pull request fixes.
=> Fix broken URL to `TensorFlow.Core` docs.

tensorflow/src/TensorFlow/Internal/FFI.hs, tensorflow/src/TensorFlow/Internal/Raw.chs, tensorflow/src/TensorFlow/Output.hs, tensorflow/src/TensorFlow/Session.hs
This is a prerequisite for supporting SavedModel.
=> Migrate from TF_DeprecatedSession to TF_Session

tensorflow/src/TensorFlow/Core.hs, tensorflow/src/TensorFlow/Internal/FFI.hs, tensorflow/src/TensorFlow/Internal/Raw.chs, tensorflow/src/TensorFlow/Session.hs
=> Support loading a Session from a SavedModel

tensorflow-core-ops/Setup.hs
hsSourceDirs is now a list of SymbolicPath instead of FilePath.
This is needed to unbreak the Nix package, where Cabal 3 gets used.
=> Support Cabal 3.

tensorflow-core-ops/Setup.hs
I was still getting build failures of `tensorflow-core-ops` even after #289:
```
/home/johannes/ag/anomaly-detection/ghc-90/haskell/tensorflow-core-ops/dist-newstyle/build/x86_64-linux/ghc-9.0.2/tensorflow-core-ops-0.3.0.0/setup/setup.hs:32:1: error:
Could not find module ‘Distribution.Utils.Path’
Perhaps you meant
Distribution.Utils.IOData (from Cabal-3.4.1.0)
Distribution.Utils.MD5 (from Cabal-3.4.1.0)
Distribution.Utils.Base62
Use -v (or `:set -v` in ghci) to see a list of the files searched for.
|
32 | import Distribution.Utils.Path (unsafeMakeSymbolicPath)
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Checking hackage, the earliest exposure of the `Distribution.Utils.Path` module is in version 3.6 (https://hackage.haskell.org/package/Cabal-3.6.0.0) instead of 3.1 as …
=> Fix min version guard for Cabal

tensorflow-ops/src/TensorFlow/Gradient.hs
I was getting these cryptic errors when building `tensorflow-ops` with GHC 9.0.2, but I can't really pinpoint what packages/versions are responsible:
```
[4 of 8] Compiling TensorFlow.Gradient ( src/TensorFlow/Gradient.hs, /home/johannes/ag/anomaly-detection/ghc-90/haskell/tensorflow-ops/dist-newstyle/build/x86_64-linux/ghc-9.0.2/tensorflow-ops-0.3.0.0/build/TensorFlow/Gradient.o, /home/johannes/ag/anomaly-detection/ghc-90/haskell/tensorflow-ops/dist-newstyle/build/x86_64-linux/ghc-9.0.2/tensorflow-ops-0.3.0.0/build/TensorFlow/Gradient.dyn_o )
src/TensorFlow/Gradient.hs:171:46: error:
• Couldn't match type: Lens' (Map NodeName v1) (Maybe v1)
with: lens-family-core-2.1.2:Lens.Family.FoldLike
(Maybe FGL.Node) (Map NodeName FGL.Node) t0 (Maybe FGL.Node) b0
Expected: NodeName
-> …
```
=> Fix lens errors

README.md, ci_build/Dockerfile, docker/Dockerfile, docker/gpu/Dockerfile, stack.yaml, tensorflow-proto/tensorflow-proto.cabal, tensorflow/src/TensorFlow/Internal/FFI.hs
Commit https://github.com/tensorflow/tensorflow/commit/78d8fdde71b9a0dc2e1919194f071ba8c222e1d5 renamed the status fields from the `TF_` prefix to `TSL_`, though there are define's in place to keep the old names, the Haskell FFI generator picks up the new names, leading to compile errors.
To fix compilation, and be forward compatible, I renamed the fields, which means this branch is not compatible with older tensorflow versions, but I don't know how to make it so without ugly hacks.
=> Update to TensorFlow 2.12
